In [6]:
import numpy as np

class PowerMethod:
    def __init__(self, matrix, tekrar=100, threshold=1e-6):
        self.matrix = matrix
        self.n = len(matrix)
        self.tekrar = tekrar
        self.threshold = threshold
        self.X0 = np.ones(self.n) / self.n
        self.eigenvalue = 0

    def calculate(self):
        for _ in range(self.tekrar):
            y = np.dot(self.matrix, self.X0)
            X1 = y / np.max(np.abs(y))
            self.eigenvalue = np.dot(self.X0, y) / np.dot(self.X0, self.X0)

            if np.linalg.norm(X1 - self.X0) < self.threshold:
                return self.eigenvalue, X1

            self.X0 = X1

def main():
    use_test_case = input("Using Testcase? (y/n)\n") == "y"

    if use_test_case:
        A = np.array([[8, -6, 2], [-6, 7, -4], [2, -4, 3]])
    else:
        n = int(input("Dimension of matrix: "))
        A = np.zeros((n, n))
        print("Enter matrix:")
        for i in range(n):
            A[i] = [float(x) for x in input().split()]

    instance = PowerMethod(A)
    eigenvalue, eigenvector = instance.calculate()

    print("\nDominant Eigenvector:", eigenvector)
    print("\nDominant Eigenvalue:", eigenvalue, "=====> ≈ ", round(eigenvalue), "\n")

if __name__ == "__main__":
    main()

Using Testcase? (y/n)
n
Dimension of matrix: 3
Enter matrix:
8 -6 2
-6 7 -4
2 -4 3

Dominant Eigenvector: [ 1.         -0.99999985  0.49999985]

Dominant Eigenvalue: 14.99999999999685 =====> ≈  15 



In [1]:
import numpy as np

class GramSchmidt:
    def __init__(self, n):
        self.n = n
        self.A = np.zeros((n, n))
        self.Q = np.zeros((n, n))
        self.R = np.zeros((n, n))

    def input(self):
        print("Enter matrix:")
        for i in range(self.n):
            self.A[i] = [float(x) for x in input().split()]

    def use_testcase(self):
        self.A = np.array([[1, 3, 5], [1, 3, 1], [2, -1, 7]], dtype=float)

    def gram_schmidt(self):
        for i in range(self.n):
            u = self.A[:, i]
            if i > 0:
                for j in range(i):
                    u -= np.dot(self.Q[:, j], self.A[:, i]) * self.Q[:, j]
            self.Q[:, i] = u / np.linalg.norm(u)

            for j in range(i, self.n):
                self.R[i, j] = np.dot(self.Q[:, i], self.A[:, j])

    def show_result(self):
        print("\nMatrix Q:")
        print(np.array2string(self.Q, formatter={'float_kind': lambda x: "%.10f" % x}))
        print("\nMatrix R:")
        print(np.array2string(self.R, formatter={'float_kind': lambda x: "%.10f" % x}))

def main():
    use_test_case = input("Using Testcase? (y/n)\n") == "y"

    if use_test_case:
        qr = GramSchmidt(3)
        qr.use_testcase()
    else:
        n = int(input("Dimension of matrix: "))
        qr = GramSchmidt(n)
        qr.input()

    qr.gram_schmidt()
    qr.show_result()

if __name__ == "__main__":
    main()

Using Testcase? (y/n)
y

Matrix Q:
[[0.4082482905 0.5773502692 0.7071067812]
 [0.4082482905 0.5773502692 -0.7071067812]
 [0.8164965809 -0.5773502692 -0.0000000000]]

Matrix R:
[[2.4494897428 1.6329931619 8.1649658093]
 [0.0000000000 4.0414518843 -0.5773502692]
 [0.0000000000 0.0000000000 2.8284271247]]
